### ISSUE TITLE
Feature request - negative Backbone

### ISSUE THREAD

**Issue by cslotboom** [cslotboom/hysteresis#28]
It was requested by @sahilkur36 to be able to return the positive and negative backbone curve. Some Hysteresis are asymmetrical and this would be a useful feature.

![image](https://github.com/cslotboom/hysteresis/assets/50510141/1221fe42-217f-4e43-8217-b7a95839c856)

**Comment by cslotboom** [comment]
@sahilkur36 There is currently no function that returns the negative backbone, I'll look at making that an option on the backbone functions in the future. 

However, if you look at the getAvgBackbone function, some of the code might be useful for you, see code below. Before the next release, you should be able to extract a positive and negative backbone by reversing your hysteresis. This is kind of hacky, but hopefully works in the short term while I add that functionality.

![image](https://github.com/cslotboom/hysteresis/assets/50510141/6ad89a64-4622-4b7c-900c-c7b194bb5898)

**Comment by cslotboom** [comment]
Actually, I just realized negative backbone is returned by getAvgBackbone...
Does that solve your issue?

**Comment by sahilkur36** [comment]
Thank you for your response sir. getAvgBackbone function returns the avg
backbone, postive backbone and negative backbone, but the thing is all the
all the values are positive in negative backbone. To extract the data and
to plot in on negative side its bit troublesome.

It will be really awesome if you could add another function to get whole
backbone curve.

I will be waiting for that Sie. Thank you for your time.


Regards,
Sahil

**Comment by cslotboom** [comment]
Hey, you should be able to reverse the negative all the points on the backbone curve, then combine that with the positive backbone curve - see the first line code above! I'll consider options for this though.

**Comment by cslotboom** [comment]
Updated getBackboneCurve in 89b1a2e, issue will be closed in next minor version release.

**Comment by VahedCivil** [comment]
Hello everybody
Just do this:

bavg, bpos, bneg = hys.getAvgBackbone(myHys, LPsteps, returnPeaks=True)
backBone = np.concatenate((np.flip(-bneg.xy, 0) , bpos), axis=0)

fig, ax = plt.subplots()
line1 = myHys.plot(linewidth = 0.7, label = 'Raw Data')
line2 = bavg.plot(linestyle = '-.', label =  'Avg. Backbone')
ax.plot(backBone[:, 0], backBone[:, 1], linestyle = '-.', label =  'Backbone')

Regards
Vahed

**Comment by cslotboom** [comment]
Also a valid solution that will work in the interim - thanks Vahed!

**Comment by cslotboom** [comment]
@sahilkur36 
This should be addressed in 2.0.1, there is now a flag for "includeNegative" if you want to get both sides of the curve by default. Let me know if you still have trouble!
https://github.com/cslotboom/hysteresis/blob/89b1a2e31cef0a8b154f3ab1a95cf8c6b13f3853/src/envelope.py#L71-L73
