### ISSUE TITLE
Save EPPP curve

### ISSUE THREAD

**Issue by HuanruZhu** [cslotboom/Hysteresis#32]
Hi Christian,

Greetings from Huanru. As usual, your Hysteresis tool saved my life in processing the pushover curve. Thank you for all the effort.

I wonder that if there any way to save the bilinear curve or at least the effective yield displacement after we managed to obtain the EPPP bilinear curve for a pushover curve. I noticed the "myEEEP"  is a simple curve object. Any hints will be so helpful!

    xy = np.column_stack([roof_disp, base_shear])
    myHys = hys.Hysteresis(xy)
    myEEEP = hys.fitEEEP(myHys)    # Fit the EEEP to the curve
    line1 = myHys.plot(linewidth=1, label='NLSA')
    line3 = myEEEP.plot(color='black', label='EEEP Curve', linewidth=2)
    plt.minorticks_on()
    plt.grid(which='major', color='grey', linewidth=0.5, alpha=0.8)
    plt.grid(which='minor', linewidth=0.5, alpha=0.4)
    plt.legend(loc='lower right',prop={'family': 'Times New Roman', "size": 14}, frameon=False)
    plt.xlabel('Roof drift ratio (%)', **csfont)
    plt.ylabel('base shear (kN)', **csfont)
    plt.xlim(0, 5)
    plt.ylim(0, )
    plt.show()

Sincerely
Huanru

**Comment by HuanruZhu** [comment]
my bad. to export the corner points. Command myEEEP.x can be used. thanks!

**Comment by cslotboom** [comment]
Hey yeah I was going to suggest either using .x or .xy - glad you figured it out! Let me know if you have any other questions or want new features added and and I'll do my best to help!
